// Persons actions

export const ALERT_DELETE_PERSON = 'ALERT_DELETE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
export const TOGGEL_PERSON = 'TOGGEL_PERSON';
export const HIDE_COCKPIT = 'HIDE_COCKPIT';
export const HANDLE_NAME = 'HANDLE_NAME';
export const AUTHENTICATED = 'AUTHENTICATED';

// News actions

export const NEWS_PAYLOAD_SUCCESS = 'NEWS_PAYLOAD_SUCCESS';
export const NEWS_PAYLOD_FAIL = 'NEWS_PAYLOD_FAIL';
export const SET_COMMENT_NAME = 'SET_COMMENT_NAME';
export const SET_COMMENT_BODY = 'SET_COMMENT_BODY'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const COMMENT_POSTED = 'COMMENT_POSTED';
export const COMMENT_POST_FAILED = 'COMMENT_POST_FAILED';